### ISSUE TITLE
Select a Photodector

### ISSUE THREAD

**Issue by BrianLandry** [felixekn/Team04_MicrobeControllers#1]

**Comment by felixekn** [comment]
http://www.digikey.com/product-detail/en/TSL237S-LF/TSL237-S-LF-ND/3095041

**Comment by felixekn** [comment]
We should purchase 4-6 of these since the lab doesn't have any left and it's likely we'll burn a few out during prototyping.

**Comment by BrianLandry** [comment]
[Digi-Key - Online Order Summary.pdf](https://github.com/felixekn/Team04_MicrobeControllers/files/13600/Digi-Key.-.Online.Order.Summary.pdf)

Ordered 4
