### ISSUE TITLE
Select a light source

### ISSUE THREAD

**Issue by BrianLandry** [felixekn/Team04_MicrobeControllers#2]

**Comment by felixekn** [comment]
http://www.digikey.com/product-search/en?KeyWords=VLM-650-03-LPA-ND&WT.z_header=search_go

**Comment by felixekn** [comment]
The laser's operating temp is 12-30ºC so if we use this laser, the OD detector can't be put into the incubator.

**Comment by BrianLandry** [comment]
Why aren't we using the lasers we are using in lab? And did you check to
see if we have any spares?

**Comment by felixekn** [comment]
These are the lasers that we have in lab and I checked and we do have some for us to use.
