### ISSUE TITLE
Select a button input

### ISSUE THREAD

**Issue by BrianLandry** [felixekn/Team04_MicrobeControllers#4]

**Comment by BrianLandry** [comment]
Top canidate at the moment https://www.sparkfun.com/products/9190

**Comment by felixekn** [comment]
I like.

**Comment by BrianLandry** [comment]
ordered

**Comment by BrianLandry** [comment]
For recordkeeping
[SparkFun Electronics Order #2426923 Invoice.pdf](https://github.com/felixekn/Team04_MicrobeControllers/files/11489/SparkFun.Electronics.Order.2426923.Invoice.pdf)
