### ISSUE TITLE
Select an LED interface

### ISSUE THREAD

**Issue by BrianLandry** [felixekn/Team04_MicrobeControllers#5]

**Comment by BrianLandry** [comment]
This is the current top option for an LED screen
https://www.sparkfun.com/products/11644

**Comment by felixekn** [comment]
Looks good. If for whatever reason we need a stripped down screen without its own microcontroller, we can buy this one:
http://www.digikey.com/product-detail/en/LDQ-M512RI/67-1440-ND/252634 http://www.digikey.com/product-detail/en/LDQ-M512RI/67-1440-ND/252634

-Felix

**Comment by BrianLandry** [comment]
Yeah I saw those on sparkfun, they are just much more of a pain to program.

**Comment by BrianLandry** [comment]
Connect via one of these https://www.sparkfun.com/products/9915?_ga=1.137509680.1693251387.1432681039

**Comment by felixekn** [comment]
What would we be connecting with this? The button?

**Comment by BrianLandry** [comment]
ordered
